kinematics:
  left_arm_adapter:
    x: 0.0
    y: 0.015
    z: 0.38
    roll: -1.5703
    pitch: 0.0
    yaw: 0.0
  right_arm_adapter:
    x: 0.0
    y: -0.015
    z: 0.38
    roll: 1.5703
    pitch: 3.14159
    yaw: 0.0
